### ISSUE TITLE
Contribution question

### ISSUE THREAD

**Issue by till** [mrichman/godnsbl#2]
Hey! 

Thanks for posting "godnsbl".

I had planned to use your code in a Prometheus exporter, but ended up rewriting part of it using another dns library and making it more of a library to use in other tools.

I understand (or think), you wrote this to be a "CLI tool". Would you still like a PR? And are you okay with introducing another dependency?

Till

**Comment by mrichman** [comment]
Hi there! I'm thrilled to hear that you find this useful. I pretty much abandoned this after I wrote it, as it was mostly a learning exercise for me. If you want to send me a PR, feel free. Thanks!
