### ISSUE TITLE
Getting listed:true for all RBL lookup

### ISSUE THREAD

**Issue by ashishtiwari1993** [mrichman/godnsbl#3]
It is useful library for me. I am planning to use it. But i faced some issue while i was testing this.

## 1. Getting all result with `listed:true`

Some of my findings:

I took domain which was already blacklisted on `b.barracudacentral.org`  And printed the Result in `query` function from `godnsbl.go`

```go
func query(rbl string, host string, r *Result) {
    r.Listed = false
    r.Rbl = rbl

    lookup := fmt.Sprintf("%s.%s", host, rbl)

    res, err := net.LookupHost(lookup)
    fmt.Println(res)

    if len(res) > 0 {
        r.Listed = true
        txt, _ := net.LookupTXT(lookup)
        if len(txt) > 0 {
            r.Text = txt[0]
        }
    }
    if err != nil {
        r.Error = true
        r.ErrorType = err
    }

    return
}
```

I run lookup for only `b.barracudacentral.org` and got below IP:
`[127.0.0.2]`

After this i run for `bl.0spam.org` where that domain was not listed and got below IP:
`[96.126.123.244 45.79.19.196 198.58.118.167 45.56.79.23 45.33.23.183 45.33.2.79]`

I did some research and found that whenever domain will be blacklisted the RBL will return IP something like:
`127.0.0.*`

In above code we are evaluating basis of `len(res)`

## 2. Need to display RBL domain in output

In JSON response we should return the RBL domain name against which we perform lookup. Sample response:

```json
{
      "rbl":"b.barracudacentral.org",
      "address":"X.X.X.X",
      "listed":true,
      "text":"http://www.barracudanetworks.com/reputation/?pr=1\u0026ip=X.X.X.X",
      "error":false,
      "error_type":null
}
```

### Please verify above both the issue so that I can raise my PR. 

Thanks

**Comment by mrichman** [comment]
I really don't use or maintain this library, so feel free to send me a PR if you think something should be improved. Thanks!
